### PR TITLE
Basic CSS changes 

### PR DESCRIPTION
**Pull request by madm234**
1. I have changed overall css ,you can see in the attached image.
2. In input box numbers now appears from right to left(according to a basic real-life calculator).
3. 'Numbers' and 'equals to' color changed so that they look different from others.
4. Responsive.

image

### CODE REVIEW

**Comment by madm234** [comment]
@sanskarmalkhede If you liked this design do merge this under hactoberfest. If not ,then suggest the changes.

**Comment by sanskarmalkhede** [comment]
The overall design looks good👍 But I think the color palette looks like every other calculator app out there. If possible use a popping color palette.

**Comment by madm234** [comment]
> The overall design looks good👍 But I think the color palette looks like every other calculator app out there. If possible use a popping color palette.

Sure. I only chose this background color cause I found it a descent dark color. However I would now change it to popping one.

**Comment by madm234** [comment]
@sanskarmalkhede Is it fine now?

image

**Pull request merged**
