### PR TITLE
precision controller 

### PR DESCRIPTION
**Pull request by ishan-nahid**
added precision controller.
This feature will allow users to control how many decimal places are displayed in the results.
User need to set the precision number before the calculations.

### CODE REVIEW

**Comment by sanskarmalkhede** [comment]
Can't see any difference, can you attach screenshots or give a detailed description on how this feature works.

**Comment by ishan-nahid** [comment]
you just need to assign how many digits after decimal point you want to see. 







anything else?

**Comment by sanskarmalkhede** [comment]
Center the text field, its not a good design. Functionality is perfect.

**Comment by ishan-nahid** [comment]
updated_middle

now?

**Comment by ishan-nahid** [comment]
check now and review, marge. 
add hacktoberfest-accepted label.

**Pull request merged**
