### PR TITLE
improved css with better response to mobile-veiw

### PR DESCRIPTION
**Pull request by AbdulRaoof13**
changed css and a bit of html to make it look better improved its visibility on mobile too please review pr and merge it with label hacktoberfest thanks

### CODE REVIEW

**Comment by AbdulRaoof13** [comment]
solves issue #13 too

**Comment by sanskarmalkhede** [comment]
Can you please attach screenshots for the better understanding.

**Comment by AbdulRaoof13** [comment]
image
image

**Comment by sanskarmalkhede** [comment]
Your PR is merged. Thank you for your contribution 🙂 
If you have more issues please feel to create them and do not forget to star the repository. 
Happy coding 👍

**Pull request merged**
